export async function seed(knex) {
  const workoutUids = (await knex("workouts")).map((workout) => workout.uid);

  await knex("exercises").del();
  await knex("exercises").insert([
    {
      workout_uid: workoutUids[0],
      title: "C&P",
      weight: 24,
      weight_unit: "kg",
      sets: 5,
      reps: 10,
      reps_display: "L/R",
      comment: "1 of 2 exercises",
      start_time: knex.fn.now(),
      end_time: null,
    },
    {
      workout_uid: workoutUids[0],
      title: "Squat",
      weight: 24,
      weight_unit: "kg",
      sets: 10,
      reps: 10,
      reps_display: "std",
      comment: "2 of 2 exercises",
      start_time: knex.fn.now(),
      end_time: null,
    },
    {
      workout_uid: workoutUids[1],
      title: "TGU",
      weight: 24,
      weight_unit: "kg",
      sets: 10,
      reps: 2,
      reps_display: "L/R",
      comment: "EMOM. 1 of 1 exercises",
      start_time: knex.fn.now(),
      end_time: null,
    },
    {
      workout_uid: workoutUids[2],
      title: "Swing",
      weight: 16,
      weight_unit: "kg",
      sets: 10,
      reps: 20,
      reps_display: "std",
      comment: "EMOM. 1 of 1 exercises",
      start_time: knex.fn.now(),
      end_time: null,
    },
    {
      workout_uid: workoutUids[2],
      title: "SA Swing",
      weight: 18.0,
      weight_unit: "kg",
      sets: 10,
      reps: 10,
      reps_display: "L/R",
      comment: "1 of 1 exercises",
      start_time: knex.fn.now(),
      end_time: null,
    },
    {
      workout_uid: workoutUids[3],
      title: "Squat",
      weight: 35,
      weight_unit: "lb",
      sets: 10,
      reps: 10,
      reps_display: "std",
      comment: "1 of 1 exercises",
      start_time: knex.fn.now(),
      end_time: null,
    },
    {
      workout_uid: workoutUids[4],
      title: "Press",
      weight: 28,
      weight_unit: "kg",
      sets: 10,
      reps: 2,
      reps_display: "std",
      comment: "1 of 1 exercises",
      start_time: knex.fn.now(),
      end_time: null,
    },
    {
      workout_uid: workoutUids[5],
      title: "Swing",
      weight: 32,
      weight_unit: "kg",
      sets: 10,
      reps: 20,
      reps_display: "std",
      comment: "1 of 1 exercises",
      start_time: knex.fn.now(),
      end_time: null,
    },
  ]);
}
